package net.zhoubian.app.model;

/**
 * Activity generated by MyEclipse Persistence Tools
 */

public class Activity implements java.io.Serializable {

	// Fields

	private Long activityId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Activity() {
	}

	/** full constructor */
	public Activity(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}