package net.zhoubian.app.model;

import java.util.Date;

/**
 * Album generated by MyEclipse Persistence Tools
 */

public class Album implements java.io.Serializable {

	// Fields

	private Long albumId;

	private Long uid;

	private String albumName;

	private Short picnum;

	private String password;

	private Date updateTime;

	// Constructors

	/** default constructor */
	public Album() {
	}

	/** minimal constructor */
	public Album(String albumName, Short picnum, Date updateTime) {
		this.albumName = albumName;
		this.picnum = picnum;
		this.updateTime = updateTime;
	}

	/** full constructor */
	public Album(Long uid, String albumName, Short picnum, String password,
			Date updateTime) {
		this.uid = uid;
		this.albumName = albumName;
		this.picnum = picnum;
		this.password = password;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Long albumId) {
		this.albumId = albumId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	public Short getPicnum() {
		return this.picnum;
	}

	public void setPicnum(Short picnum) {
		this.picnum = picnum;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}