package net.zhoubian.app.model;

/**
 * Blog generated by MyEclipse Persistence Tools
 */

public class Blog implements java.io.Serializable {

	// Fields

	private Long blogId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Blog() {
	}

	/** full constructor */
	public Blog(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getBlogId() {
		return this.blogId;
	}

	public void setBlogId(Long blogId) {
		this.blogId = blogId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}