package net.zhoubian.app.model;

/**
 * CategoryStruct generated by MyEclipse Persistence Tools
 */

public class CategoryStruct implements java.io.Serializable {

	// Fields

	private Integer id;

	private String categoryId;

	private Integer infoMetaId;

	private Integer sort;

	// Constructors

	/** default constructor */
	public CategoryStruct() {
	}

	/** full constructor */
	public CategoryStruct(String categoryId, Integer infoMetaId, Integer sort) {
		this.categoryId = categoryId;
		this.infoMetaId = infoMetaId;
		this.sort = sort;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getInfoMetaId() {
		return this.infoMetaId;
	}

	public void setInfoMetaId(Integer infoMetaId) {
		this.infoMetaId = infoMetaId;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}