package net.zhoubian.app.model;

import java.util.Date;

/**
 * CategoryHot generated by MyEclipse Persistence Tools
 */

public class CategoryHot implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer categoryId;

	private String cityId;

	private Integer sort;

	private Date createTime;

	// Constructors

	/** default constructor */
	public CategoryHot() {
	}

	/** full constructor */
	public CategoryHot(Integer categoryId, String cityId, Integer sort,
			Date createTime) {
		this.categoryId = categoryId;
		this.cityId = cityId;
		this.sort = sort;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}