package net.zhoubian.app.model;

/**
 * City generated by MyEclipse Persistence Tools
 */

public class City implements java.io.Serializable {

	// Fields

	private String cityId;

	private String cityName;

	private String provinceId;
	
	private Float longitude;
	
	private Float latitude;
	
	private Float ratio;

	private String pinyin;
	// Constructors

	/** default constructor */
	public City() {
	}

	/** full constructor */
	public City(String cityName, String provinceId,Float longitude,Float latitude,Float ratio,String pinyin) {
		this.cityName = cityName;
		this.provinceId = provinceId;
		this.longitude = longitude;
		this.latitude = latitude;
		this.ratio = ratio;
		this.pinyin = pinyin;
	}

	// Property accessors

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public Float getLongitude() {
		return longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getRatio() {
		return ratio;
	}

	public void setRatio(Float ratio) {
		this.ratio = ratio;
	}
	
	public String getPinyin() {
		return pinyin;
	}
	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

}