package net.zhoubian.app.model;

/**
 * City generated by MyEclipse Persistence Tools
 */

public class City implements java.io.Serializable {

	// Fields

	private String cityId;

	private String cityName;

	private String provinceId;

	// Constructors

	/** default constructor */
	public City() {
	}

	/** full constructor */
	public City(String cityName, String provinceId) {
		this.cityName = cityName;
		this.provinceId = provinceId;
	}

	// Property accessors

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

}