package net.zhoubian.app.model;

/**
 * Class generated by MyEclipse Persistence Tools
 */

public class Class implements java.io.Serializable {

	// Fields

	private String classId;

	private String className;

	private Integer sort;

	// Constructors

	/** default constructor */
	public Class() {
	}

	/** full constructor */
	public Class(String className, Integer sort) {
		this.className = className;
		this.sort = sort;
	}

	// Property accessors

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}