package net.zhoubian.app.model;

import java.util.List;

/**
 * Clazz generated by MyEclipse Persistence Tools
 */

public class Clazz implements java.io.Serializable {

	// Fields

	private String classId;

	private String className;

	private Integer sort;
	
	private List<SubClass> subClasses;
	// Constructors

	/** default constructor */
	public Clazz() {
	}

	/** full constructor */
	public Clazz(String className, Integer sort) {
		this.className = className;
		this.sort = sort;
	}

	// Property accessors

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public void setSubClasses(List<SubClass> subClasses) {
		this.subClasses = subClasses;
	}
	public List<SubClass> getSubClasses() {
		return subClasses;
	}
}