package net.zhoubian.app.model;

/**
 * Comment generated by MyEclipse Persistence Tools
 */

public class Comment implements java.io.Serializable {

	// Fields

	private Long commentId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Comment() {
	}

	/** full constructor */
	public Comment(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}