package net.zhoubian.app.model;

/**
 * Diary generated by MyEclipse Persistence Tools
 */

public class Diary implements java.io.Serializable {

	// Fields

	private Long diaryId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Diary() {
	}

	/** full constructor */
	public Diary(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getDiaryId() {
		return this.diaryId;
	}

	public void setDiaryId(Long diaryId) {
		this.diaryId = diaryId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}