package net.zhoubian.app.model;

/**
 * Enterprise generated by MyEclipse Persistence Tools
 */

public class Enterprise implements java.io.Serializable {

	// Fields

	private Integer uid;

	private String name;

	private String address;

	private String postcode;

	private String openAccBank;

	private String account;

	private String busiLicNum;

	private String representative;

	private String responsible;

	private String respPhone;

	private String ecPhone;

	private String ecMail;

	private String website;

	private Short ecProperty;

	private String remark;

	// Constructors

	/** default constructor */
	public Enterprise() {
	}

	/** minimal constructor */
	public Enterprise(String openAccBank, String account, String busiLicNum,
			String representative, Short ecProperty) {
		this.openAccBank = openAccBank;
		this.account = account;
		this.busiLicNum = busiLicNum;
		this.representative = representative;
		this.ecProperty = ecProperty;
	}

	/** full constructor */
	public Enterprise(String name, String address, String postcode,
			String openAccBank, String account, String busiLicNum,
			String representative, String responsible, String respPhone,
			String ecPhone, String ecMail, String website, Short ecProperty,
			String remark) {
		this.name = name;
		this.address = address;
		this.postcode = postcode;
		this.openAccBank = openAccBank;
		this.account = account;
		this.busiLicNum = busiLicNum;
		this.representative = representative;
		this.responsible = responsible;
		this.respPhone = respPhone;
		this.ecPhone = ecPhone;
		this.ecMail = ecMail;
		this.website = website;
		this.ecProperty = ecProperty;
		this.remark = remark;
	}

	// Property accessors

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getOpenAccBank() {
		return this.openAccBank;
	}

	public void setOpenAccBank(String openAccBank) {
		this.openAccBank = openAccBank;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getBusiLicNum() {
		return this.busiLicNum;
	}

	public void setBusiLicNum(String busiLicNum) {
		this.busiLicNum = busiLicNum;
	}

	public String getRepresentative() {
		return this.representative;
	}

	public void setRepresentative(String representative) {
		this.representative = representative;
	}

	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	public String getRespPhone() {
		return this.respPhone;
	}

	public void setRespPhone(String respPhone) {
		this.respPhone = respPhone;
	}

	public String getEcPhone() {
		return this.ecPhone;
	}

	public void setEcPhone(String ecPhone) {
		this.ecPhone = ecPhone;
	}

	public String getEcMail() {
		return this.ecMail;
	}

	public void setEcMail(String ecMail) {
		this.ecMail = ecMail;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Short getEcProperty() {
		return this.ecProperty;
	}

	public void setEcProperty(Short ecProperty) {
		this.ecProperty = ecProperty;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}