package net.zhoubian.app.model;

/**
 * Gift generated by MyEclipse Persistence Tools
 */

public class Gift implements java.io.Serializable {

	// Fields

	private Integer giftId;

	private String giftName;

	// Constructors

	/** default constructor */
	public Gift() {
	}

	/** full constructor */
	public Gift(String giftName) {
		this.giftName = giftName;
	}

	// Property accessors

	public Integer getGiftId() {
		return this.giftId;
	}

	public void setGiftId(Integer giftId) {
		this.giftId = giftId;
	}

	public String getGiftName() {
		return this.giftName;
	}

	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}

}