package net.zhoubian.app.model;

import java.util.Date;

/**
 * GroupBuyParticipate generated by MyEclipse Persistence Tools
 */

public class GroupBuyParticipate implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer gpId;

	private Long uid;

	private Date createTime;

	private String subscriptionCode;

	private String confirmCode;

	private Date confirmTime;

	// Constructors

	/** default constructor */
	public GroupBuyParticipate() {
	}

	/** full constructor */
	public GroupBuyParticipate(Integer gpId, Long uid, Date createTime,
			String subscriptionCode, String confirmCode, Date confirmTime) {
		this.gpId = gpId;
		this.uid = uid;
		this.createTime = createTime;
		this.subscriptionCode = subscriptionCode;
		this.confirmCode = confirmCode;
		this.confirmTime = confirmTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGpId() {
		return this.gpId;
	}

	public void setGpId(Integer gpId) {
		this.gpId = gpId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getSubscriptionCode() {
		return this.subscriptionCode;
	}

	public void setSubscriptionCode(String subscriptionCode) {
		this.subscriptionCode = subscriptionCode;
	}

	public String getConfirmCode() {
		return this.confirmCode;
	}

	public void setConfirmCode(String confirmCode) {
		this.confirmCode = confirmCode;
	}

	public Date getConfirmTime() {
		return this.confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

}