package net.zhoubian.app.model;

/**
 * IndexItem generated by MyEclipse Persistence Tools
 */

public class IndexItem implements java.io.Serializable {

	// Fields

	private Integer id;

	private String resourceType;

	private String resource;

	private String indexFields;

	private String storeFields;

	private String indexType;

	private Integer stopId;

	private String indexPath;

	// Constructors

	/** default constructor */
	public IndexItem() {
	}

	/** full constructor */
	public IndexItem(String resourceType, String resource, String indexFields,
			String storeFields, String indexType, Integer stopId,
			String indexPath) {
		this.resourceType = resourceType;
		this.resource = resource;
		this.indexFields = indexFields;
		this.storeFields = storeFields;
		this.indexType = indexType;
		this.stopId = stopId;
		this.indexPath = indexPath;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public String getIndexFields() {
		return this.indexFields;
	}

	public void setIndexFields(String indexFields) {
		this.indexFields = indexFields;
	}

	public String getStoreFields() {
		return this.storeFields;
	}

	public void setStoreFields(String storeFields) {
		this.storeFields = storeFields;
	}

	public String getIndexType() {
		return this.indexType;
	}

	public void setIndexType(String indexType) {
		this.indexType = indexType;
	}

	public Integer getStopId() {
		return this.stopId;
	}

	public void setStopId(Integer stopId) {
		this.stopId = stopId;
	}

	public String getIndexPath() {
		return this.indexPath;
	}

	public void setIndexPath(String indexPath) {
		this.indexPath = indexPath;
	}

}