package net.zhoubian.app.model;

import java.util.Date;

/**
 * Information generated by MyEclipse Persistence Tools
 */

public class Information implements java.io.Serializable {

	// Fields

	private Long id;

	private String title;

	private String categoryId;

	private Float longitude;

	private Float latitude;

	private Date createTime;

	private String state;

	private Integer positionId;
	
	private String indexStatus; // 索引状态，默认为0,0:未索引 ，1:已索引
	public static String UNINDEXED = "0";
	public static String INDEXED = "1";
	// Constructors

	/** default constructor */
	public Information() {
	}

	/** full constructor */
	public Information(String title, String categoryId, Float longitude,
			Float latitude, Date createTime, String state, Integer positionId) {
		this.title = title;
		this.categoryId = categoryId;
		this.longitude = longitude;
		this.latitude = latitude;
		this.createTime = createTime;
		this.state = state;
		this.positionId = positionId;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Integer getPositionId() {
		return this.positionId;
	}

	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}
	
	public void setIndexStatus(String indexStatus) {
		this.indexStatus = indexStatus;
	}
	public String getIndexStatus() {
		return indexStatus;
	}

}