package net.zhoubian.app.model;

import java.util.Date;

/**
 * Information generated by MyEclipse Persistence Tools
 */

public class Information implements java.io.Serializable {
	
	public static String UNINDEXED = "0";
	public static String INDEXED = "1";

	// Fields

	private Long id;

	private String title;

	private String categoryId;

	private Float longitude;

	private Float latitude;

	private Date createTime;

	private String state;

	private Long locationId;
	
	private String indexStatus; // 索引状态，默认为0,0:未索引 ，1:已索引
	
	private String provinceId;
	
	private String cityId;
	
	private String countyId;
	
	private String streetId;
	
	private String locationDesc;
	
	private String content;
	
	private String telephone;
	
	private String site;
	
	private Short tag1;
	
	private Short tag2;
	
	private Short tag3;
	
	private Short tag4;
	
	private Short tag5;
	
	private Short tag6;
	
	private Short tag7;
	
	private Short tag8;
	
	private Short tag9;
	
	private Short tag10;
	
	// Constructors

	/** default constructor */
	public Information() {
	}


	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}
	
	public void setIndexStatus(String indexStatus) {
		this.indexStatus = indexStatus;
	}
	public String getIndexStatus() {
		return indexStatus;
	}


	public String getProvinceId() {
		return provinceId;
	}


	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}


	public String getCityId() {
		return cityId;
	}


	public void setCityId(String cityId) {
		this.cityId = cityId;
	}


	public String getCountyId() {
		return countyId;
	}


	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}


	public String getStreetId() {
		return streetId;
	}


	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}


	public String getLocationDesc() {
		return locationDesc;
	}


	public void setLocationDesc(String locationDesc) {
		this.locationDesc = locationDesc;
	}


	public String getContent() {
		return content;
	}


	public void setContent(String content) {
		this.content = content;
	}


	public String getTelephone() {
		return telephone;
	}


	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}


	public String getSite() {
		return site;
	}


	public void setSite(String site) {
		this.site = site;
	}


	public Short getTag1() {
		return tag1;
	}


	public void setTag1(Short tag1) {
		this.tag1 = tag1;
	}


	public Short getTag2() {
		return tag2;
	}


	public void setTag2(Short tag2) {
		this.tag2 = tag2;
	}


	public Short getTag3() {
		return tag3;
	}


	public void setTag3(Short tag3) {
		this.tag3 = tag3;
	}


	public Short getTag4() {
		return tag4;
	}


	public void setTag4(Short tag4) {
		this.tag4 = tag4;
	}


	public Short getTag5() {
		return tag5;
	}


	public void setTag5(Short tag5) {
		this.tag5 = tag5;
	}


	public Short getTag6() {
		return tag6;
	}


	public void setTag6(Short tag6) {
		this.tag6 = tag6;
	}


	public Short getTag7() {
		return tag7;
	}


	public void setTag7(Short tag7) {
		this.tag7 = tag7;
	}


	public Short getTag8() {
		return tag8;
	}


	public void setTag8(Short tag8) {
		this.tag8 = tag8;
	}


	public Short getTag9() {
		return tag9;
	}


	public void setTag9(Short tag9) {
		this.tag9 = tag9;
	}


	public Short getTag10() {
		return tag10;
	}


	public void setTag10(Short tag10) {
		this.tag10 = tag10;
	}
	
	

}