package net.zhoubian.app.model;

import java.util.Date;

/**
 * InformationComment generated by MyEclipse Persistence Tools
 */

public class InformationComment implements java.io.Serializable {

	// Fields

	private Integer id;

	private Long infoId;

	private String comment;

	private Long uid;

	private Date createTime;

	private String ip;

	// Constructors

	/** default constructor */
	public InformationComment() {
	}

	/** full constructor */
	public InformationComment(Long infoId, String comment, Long uid,
			Date createTime, String ip) {
		this.infoId = infoId;
		this.comment = comment;
		this.uid = uid;
		this.createTime = createTime;
		this.ip = ip;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}