package net.zhoubian.app.model;

/**
 * InfoMetadata generated by MyEclipse Persistence Tools
 */

public class InfoMetadata implements java.io.Serializable {

	// Fields

	private Integer id;

	private String label;

	private String elementId;

	private String type;

	private Integer maxLength;

	// Constructors

	/** default constructor */
	public InfoMetadata() {
	}

	/** full constructor */
	public InfoMetadata(String label, String elementId, String type,
			Integer maxLength) {
		this.label = label;
		this.elementId = elementId;
		this.type = type;
		this.maxLength = maxLength;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getElementId() {
		return this.elementId;
	}

	public void setElementId(String elementId) {
		this.elementId = elementId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(Integer maxLength) {
		this.maxLength = maxLength;
	}

}