package net.zhoubian.app.model;

/**
 * Keywords generated by MyEclipse Persistence Tools
 */

public class Keywords implements java.io.Serializable {

	// Fields

	private Integer id;

	private String keyword;

	private String pinyin;

	private String pinyinAbstract;

	private String indexStatus; // 索引状态，默认为0,0:未索引 ，1:已索引
	public static String UNINDEXED = "0";
	public static String INDEXED = "1";
	// Constructors

	/** default constructor */
	public Keywords() {
	}

	/** full constructor */
	public Keywords(String keyword, String pinyin, String pinyinAbstract) {
		this.keyword = keyword;
		this.pinyin = pinyin;
		this.pinyinAbstract = pinyinAbstract;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getPinyin() {
		return this.pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	public String getPinyinAbstract() {
		return this.pinyinAbstract;
	}

	public void setPinyinAbstract(String pinyinAbstract) {
		this.pinyinAbstract = pinyinAbstract;
	}

	public void setIndexStatus(String indexStatus) {
		this.indexStatus = indexStatus;
	}
	public String getIndexStatus() {
		return indexStatus;
	}
}