package net.zhoubian.app.model;

/**
 * LocationType generated by MyEclipse Persistence Tools
 */

public class LocationType implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String description;

	private String metadata;

	// Constructors

	/** default constructor */
	public LocationType() {
	}

	/** minimal constructor */
	public LocationType(String name) {
		this.name = name;
	}

	/** full constructor */
	public LocationType(String name, String description, String metadata) {
		this.name = name;
		this.description = description;
		this.metadata = metadata;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

}