package net.zhoubian.app.model;

/**
 * LocationType generated by MyEclipse Persistence Tools
 */

public class LocationType implements java.io.Serializable {

	// Fields

	private Integer id;
	
	private Integer locationType;
	
	private Integer subLocType;

	private String name;

	private String description;

	private String metadata;
	
	private String iconUrl;

	// Constructors

	/** default constructor */
	public LocationType() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMetadata() {
		return this.metadata;
	}

	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}

	public Integer getLocationType() {
		return locationType;
	}

	public void setLocationType(Integer locationType) {
		this.locationType = locationType;
	}

	public Integer getSubLocType() {
		return subLocType;
	}

	public void setSubLocType(Integer subLocType) {
		this.subLocType = subLocType;
	}

	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}
	
	

}