package net.zhoubian.app.model;

import java.util.Date;

/**
 * LoginLog generated by MyEclipse Persistence Tools
 */

public class LoginLog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long uid;

	private String ip;

	private Date loginTime;

	private Date logoutTime;

	// Constructors

	/** default constructor */
	public LoginLog() {
	}

	/** full constructor */
	public LoginLog(Long uid, String ip, Date loginTime, Date logoutTime) {
		this.uid = uid;
		this.ip = ip;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

}