package net.zhoubian.app.model;

/**
 * Message generated by MyEclipse Persistence Tools
 */

public class Message implements java.io.Serializable {

	// Fields

	private Long messageId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Message() {
	}

	/** full constructor */
	public Message(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}