package net.zhoubian.app.model;

/**
 * MicroBlog generated by MyEclipse Persistence Tools
 */

public class MicroBlog implements java.io.Serializable {

	// Fields

	private Integer id;

	private Long microBlogId;

	private Long uid;

	// Constructors

	/** default constructor */
	public MicroBlog() {
	}

	/** full constructor */
	public MicroBlog(Long microBlogId, Long uid) {
		this.microBlogId = microBlogId;
		this.uid = uid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getMicroBlogId() {
		return this.microBlogId;
	}

	public void setMicroBlogId(Long microBlogId) {
		this.microBlogId = microBlogId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}