package net.zhoubian.app.model;

/**
 * Mygift generated by MyEclipse Persistence Tools
 */

public class Mygift implements java.io.Serializable {

	// Fields

	private Integer id;

	private Long uid;

	private Integer giftId;

	// Constructors

	/** default constructor */
	public Mygift() {
	}

	/** full constructor */
	public Mygift(Long uid, Integer giftId) {
		this.uid = uid;
		this.giftId = giftId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Integer getGiftId() {
		return this.giftId;
	}

	public void setGiftId(Integer giftId) {
		this.giftId = giftId;
	}

}