package net.zhoubian.app.model;

/**
 * Mypoke generated by MyEclipse Persistence Tools
 */

public class Mypoke implements java.io.Serializable {

	// Fields

	private Integer id;

	private Long uid;

	private Integer pokeId;

	private Long pokedUid;

	// Constructors

	/** default constructor */
	public Mypoke() {
	}

	/** full constructor */
	public Mypoke(Long uid, Integer pokeId, Long pokedUid) {
		this.uid = uid;
		this.pokeId = pokeId;
		this.pokedUid = pokedUid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Integer getPokeId() {
		return this.pokeId;
	}

	public void setPokeId(Integer pokeId) {
		this.pokeId = pokeId;
	}

	public Long getPokedUid() {
		return this.pokedUid;
	}

	public void setPokedUid(Long pokedUid) {
		this.pokedUid = pokedUid;
	}

}