package net.zhoubian.app.model;

import java.util.Date;

/**
 * Operator generated by MyEclipse Persistence Tools
 */

public class Operator implements java.io.Serializable {

	// Fields

	private Integer operatorId;

	private String loginName;

	private String name;

	private String password;

	private Short status;

	private Date createTime;

	// Constructors

	/** default constructor */
	public Operator() {
	}

	/** full constructor */
	public Operator(String loginName, String name, String password,
			Short status, Date createTime) {
		this.loginName = loginName;
		this.name = name;
		this.password = password;
		this.status = status;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}