package net.zhoubian.app.model;

/**
 * Pic generated by MyEclipse Persistence Tools
 */

public class Pic implements java.io.Serializable {

	// Fields

	private Long picId;

	private Long albumId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Pic() {
	}

	/** minimal constructor */
	public Pic(Long albumId) {
		this.albumId = albumId;
	}

	/** full constructor */
	public Pic(Long albumId, Long uid) {
		this.albumId = albumId;
		this.uid = uid;
	}

	// Property accessors

	public Long getPicId() {
		return this.picId;
	}

	public void setPicId(Long picId) {
		this.picId = picId;
	}

	public Long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Long albumId) {
		this.albumId = albumId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}