package net.zhoubian.app.model;

/**
 * Poke generated by MyEclipse Persistence Tools
 */

public class Poke implements java.io.Serializable {

	// Fields

	private Integer pokeId;

	private String pokeName;

	// Constructors

	/** default constructor */
	public Poke() {
	}

	/** full constructor */
	public Poke(String pokeName) {
		this.pokeName = pokeName;
	}

	// Property accessors

	public Integer getPokeId() {
		return this.pokeId;
	}

	public void setPokeId(Integer pokeId) {
		this.pokeId = pokeId;
	}

	public String getPokeName() {
		return this.pokeName;
	}

	public void setPokeName(String pokeName) {
		this.pokeName = pokeName;
	}

}