package net.zhoubian.app.model;

/**
 * Poll generated by MyEclipse Persistence Tools
 */

public class Poll implements java.io.Serializable {

	// Fields

	private Long pollId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Poll() {
	}

	/** full constructor */
	public Poll(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getPollId() {
		return this.pollId;
	}

	public void setPollId(Long pollId) {
		this.pollId = pollId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}