package net.zhoubian.app.model;

/**
 * Privilege generated by MyEclipse Persistence Tools
 */

public class Privilege implements java.io.Serializable {

	// Fields

	private String code;

	private String name;

	private String description;

	// Constructors

	/** default constructor */
	public Privilege() {
	}

	/** minimal constructor */
	public Privilege(String name) {
		this.name = name;
	}

	/** full constructor */
	public Privilege(String name, String description) {
		this.name = name;
		this.description = description;
	}

	// Property accessors

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}