package net.zhoubian.app.model;

/**
 * Province generated by MyEclipse Persistence Tools
 */

public class Province implements java.io.Serializable {

	// Fields

	private String provinceId;

	private String provinceName;

	// Constructors

	/** default constructor */
	public Province() {
	}

	/** full constructor */
	public Province(String provinceName) {
		this.provinceName = provinceName;
	}

	// Property accessors

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

}