package net.zhoubian.app.model;

/**
 * Record generated by MyEclipse Persistence Tools
 */

public class Record implements java.io.Serializable {

	// Fields

	private Long recordId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Record() {
	}

	/** full constructor */
	public Record(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}