package net.zhoubian.app.model;

/**
 * Repaste generated by MyEclipse Persistence Tools
 */

public class Repaste implements java.io.Serializable {

	// Fields

	private Long repasteId;

	private Long uid;

	// Constructors

	/** default constructor */
	public Repaste() {
	}

	/** full constructor */
	public Repaste(Long uid) {
		this.uid = uid;
	}

	// Property accessors

	public Long getRepasteId() {
		return this.repasteId;
	}

	public void setRepasteId(Long repasteId) {
		this.repasteId = repasteId;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}