package net.zhoubian.app.model;

/**
 * SiteManager generated by MyEclipse Persistence Tools
 */

public class SiteManager implements java.io.Serializable {

	// Fields

	private Long uid;

	private String name;

	private String tel;

	private String email;

	private String address;

	private String postCode;

	private String level;

	private String provinceId;

	private String cityId;

	private String countyId;

	private String streetId;

	// Constructors

	/** default constructor */
	public SiteManager() {
	}

	/** full constructor */
	public SiteManager(String name, String tel, String email, String address,
			String postCode, String level, String provinceId, String cityId,
			String countyId, String streetId) {
		this.name = name;
		this.tel = tel;
		this.email = email;
		this.address = address;
		this.postCode = postCode;
		this.level = level;
		this.provinceId = provinceId;
		this.cityId = cityId;
		this.countyId = countyId;
		this.streetId = streetId;
	}

	// Property accessors

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCountyId() {
		return this.countyId;
	}

	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}

	public String getStreetId() {
		return this.streetId;
	}

	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}

}