package net.zhoubian.app.model;

/**
 * Street generated by MyEclipse Persistence Tools
 */

public class Street implements java.io.Serializable {

	// Fields

	private String streetId;

	private String streetName;

	private String countyId;

	private String cityId;

	private String provinceId;

	// Constructors

	/** default constructor */
	public Street() {
	}

	/** full constructor */
	public Street(String streetName, String countyId, String cityId,
			String provinceId) {
		this.streetName = streetName;
		this.countyId = countyId;
		this.cityId = cityId;
		this.provinceId = provinceId;
	}

	// Property accessors

	public String getStreetId() {
		return this.streetId;
	}

	public void setStreetId(String streetId) {
		this.streetId = streetId;
	}

	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	public String getCountyId() {
		return this.countyId;
	}

	public void setCountyId(String countyId) {
		this.countyId = countyId;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

}