package net.zhoubian.app.model;

import java.util.List;

/**
 * SubClass generated by MyEclipse Persistence Tools
 */

public class SubClass implements java.io.Serializable {

	// Fields

	private String subclassId;

	private String subclassName;

	private Integer sort;

	private List<Category> categories;
	// Constructors

	/** default constructor */
	public SubClass() {
	}

	/** full constructor */
	public SubClass(String subclassName, Integer sort) {
		this.subclassName = subclassName;
		this.sort = sort;
	}

	// Property accessors

	public String getSubclassId() {
		return this.subclassId;
	}

	public void setSubclassId(String subclassId) {
		this.subclassId = subclassId;
	}

	public String getSubclassName() {
		return this.subclassName;
	}

	public void setSubclassName(String subclassName) {
		this.subclassName = subclassName;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public void setCategories(List<Category> categories) {
		this.categories = categories;
	}
	public List<Category> getCategories() {
		return categories;
	}
}