package net.zhoubian.app.model;

import java.util.List;

/**
 * SubClass generated by MyEclipse Persistence Tools
 */

public class SubClass implements java.io.Serializable {

	// Fields

	private String subclassId;

	private String subclassName;

	private Integer sort;
	
	private String nextCategory;
	
	private String tableName;
	
	private String pagePath;

	private List<Category> categories;
	// Constructors

	/** default constructor */
	public SubClass() {
	}

	/** full constructor */
	public SubClass(String subclassName, Integer sort) {
		this.subclassName = subclassName;
		this.sort = sort;
	}

	// Property accessors

	public String getSubclassId() {
		return this.subclassId;
	}

	public void setSubclassId(String subclassId) {
		this.subclassId = subclassId;
	}

	public String getSubclassName() {
		return this.subclassName;
	}

	public void setSubclassName(String subclassName) {
		this.subclassName = subclassName;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public void setCategories(List<Category> categories) {
		this.categories = categories;
	}
	public List<Category> getCategories() {
		return categories;
	}

	public String getNextCategory() {
		return nextCategory;
	}

	public void setNextCategory(String nextCategory) {
		this.nextCategory = nextCategory;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getPagePath() {
		return pagePath;
	}

	public void setPagePath(String pagePath) {
		this.pagePath = pagePath;
	}
	
	
}