package net.zhoubian.app.model;

/**
 * SystemParameters generated by MyEclipse Persistence Tools
 */

public class SystemParameters implements java.io.Serializable {

	// Fields

	private Integer id;

	private String paramName;

	private String paramValue;

	// Constructors

	/** default constructor */
	public SystemParameters() {
	}

	/** full constructor */
	public SystemParameters(String paramName, String paramValue) {
		this.paramName = paramName;
		this.paramValue = paramValue;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

}