package net.zhoubian.app.model;

import java.util.Map;

// Generated 2010-12-14 7:15:15 by Hibernate Tools 3.2.4.GA

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private int tagId;
	private String tagName;
	private String categoryId;
	private String fieldName;
	private String tagSpec;
	private Map<String,String> items;
	public Tag() {
	}

	public Tag(int tagId, String tagName, String categoryId, String fieldName,
			String tagSpec) {
		this.tagId = tagId;
		this.tagName = tagName;
		this.categoryId = categoryId;
		this.fieldName = fieldName;
		this.tagSpec = tagSpec;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getTagSpec() {
		return this.tagSpec;
	}

	public void setTagSpec(String tagSpec) {
		this.tagSpec = tagSpec;
	}

	public Map<String, String> getItems() {
		return items;
	}

	public void setItems(Map<String, String> items) {
		this.items = items;
	}
	
	
}
