package net.zhoubian.app.model;

import java.util.Date;

/**
 * TopicHot generated by MyEclipse Persistence Tools
 */

public class TopicHot implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer topicId;

	private String content;

	private String cityId;

	private Integer sort;

	private Date createTime;

	// Constructors

	/** default constructor */
	public TopicHot() {
	}

	/** full constructor */
	public TopicHot(Integer topicId, String content, String cityId,
			Integer sort, Date createTime) {
		this.topicId = topicId;
		this.content = content;
		this.cityId = cityId;
		this.sort = sort;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}