package net.zhoubian.app.model;

import java.util.Date;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private Long uid;

	private Long upperUid;

	private String loginName;

	private String name;

	private String aboutMe;

	private String birthday;

	private Long currentLocationId;

	private Long defaultLocationId;

	private Long homeLocationId;

	private String password;

	private String email;

	private String homeStreetId;

	private String homeCountyId;

	private String homeCityId;

	private String homeProvinceId;

	private String homeCountryId;

	private Short sex;

	private Date createTime;

	private Integer totalPoints;

	private Integer currentPoints;

	private Short userType;

	private String statusMessage;

	private Date statusTime;

	private Short status;

	private Integer grade;

	private Integer buyCredit;

	// Constructors

	/** default constructor */
	public User() {
	}

	/** minimal constructor */
	public User(String loginName, String password, String email, Short sex,
			Date createTime, Short userType, Short status, Integer grade) {
		this.loginName = loginName;
		this.password = password;
		this.email = email;
		this.sex = sex;
		this.createTime = createTime;
		this.userType = userType;
		this.status = status;
		this.grade = grade;
	}

	/** full constructor */
	public User(Long upperUid, String loginName, String name, String aboutMe,
			String birthday, Long currentLocationId, Long defaultLocationId,
			Long homeLocationId, String password, String email,
			String homeStreetId, String homeCountyId, String homeCityId,
			String homeProvinceId, String homeCountryId, Short sex,
			Date createTime, Integer totalPoints, Integer currentPoints,
			Short userType, String statusMessage, Date statusTime,
			Short status, Integer grade, Integer buyCredit) {
		this.upperUid = upperUid;
		this.loginName = loginName;
		this.name = name;
		this.aboutMe = aboutMe;
		this.birthday = birthday;
		this.currentLocationId = currentLocationId;
		this.defaultLocationId = defaultLocationId;
		this.homeLocationId = homeLocationId;
		this.password = password;
		this.email = email;
		this.homeStreetId = homeStreetId;
		this.homeCountyId = homeCountyId;
		this.homeCityId = homeCityId;
		this.homeProvinceId = homeProvinceId;
		this.homeCountryId = homeCountryId;
		this.sex = sex;
		this.createTime = createTime;
		this.totalPoints = totalPoints;
		this.currentPoints = currentPoints;
		this.userType = userType;
		this.statusMessage = statusMessage;
		this.statusTime = statusTime;
		this.status = status;
		this.grade = grade;
		this.buyCredit = buyCredit;
	}

	// Property accessors

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Long getUpperUid() {
		return this.upperUid;
	}

	public void setUpperUid(Long upperUid) {
		this.upperUid = upperUid;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Long getCurrentLocationId() {
		return this.currentLocationId;
	}

	public void setCurrentLocationId(Long currentLocationId) {
		this.currentLocationId = currentLocationId;
	}

	public Long getDefaultLocationId() {
		return this.defaultLocationId;
	}

	public void setDefaultLocationId(Long defaultLocationId) {
		this.defaultLocationId = defaultLocationId;
	}

	public Long getHomeLocationId() {
		return this.homeLocationId;
	}

	public void setHomeLocationId(Long homeLocationId) {
		this.homeLocationId = homeLocationId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHomeStreetId() {
		return this.homeStreetId;
	}

	public void setHomeStreetId(String homeStreetId) {
		this.homeStreetId = homeStreetId;
	}

	public String getHomeCountyId() {
		return this.homeCountyId;
	}

	public void setHomeCountyId(String homeCountyId) {
		this.homeCountyId = homeCountyId;
	}

	public String getHomeCityId() {
		return this.homeCityId;
	}

	public void setHomeCityId(String homeCityId) {
		this.homeCityId = homeCityId;
	}

	public String getHomeProvinceId() {
		return this.homeProvinceId;
	}

	public void setHomeProvinceId(String homeProvinceId) {
		this.homeProvinceId = homeProvinceId;
	}

	public String getHomeCountryId() {
		return this.homeCountryId;
	}

	public void setHomeCountryId(String homeCountryId) {
		this.homeCountryId = homeCountryId;
	}

	public Short getSex() {
		return this.sex;
	}

	public void setSex(Short sex) {
		this.sex = sex;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(Integer totalPoints) {
		this.totalPoints = totalPoints;
	}

	public Integer getCurrentPoints() {
		return this.currentPoints;
	}

	public void setCurrentPoints(Integer currentPoints) {
		this.currentPoints = currentPoints;
	}

	public Short getUserType() {
		return this.userType;
	}

	public void setUserType(Short userType) {
		this.userType = userType;
	}

	public String getStatusMessage() {
		return this.statusMessage;
	}

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}

	public Date getStatusTime() {
		return this.statusTime;
	}

	public void setStatusTime(Date statusTime) {
		this.statusTime = statusTime;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public Integer getBuyCredit() {
		return this.buyCredit;
	}

	public void setBuyCredit(Integer buyCredit) {
		this.buyCredit = buyCredit;
	}

}