package net.zhoubian.app.model;

/**
 * UserPrivilege generated by MyEclipse Persistence Tools
 */

public class UserPrivilege implements java.io.Serializable {

	// Fields

	private Integer id;

	private String code;

	private Long uid;

	// Constructors

	/** default constructor */
	public UserPrivilege() {
	}

	/** full constructor */
	public UserPrivilege(String code, Long uid) {
		this.code = code;
		this.uid = uid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

}