package net.zhoubian.app.model;

import java.util.Date;

/**
 * Visitor generated by MyEclipse Persistence Tools
 */

public class Visitor implements java.io.Serializable {

	// Fields

	private Integer id;

	private Long uid;

	private Date visitTime;

	private Long visitUid;

	// Constructors

	/** default constructor */
	public Visitor() {
	}

	/** full constructor */
	public Visitor(Long uid, Date visitTime, Long visitUid) {
		this.uid = uid;
		this.visitTime = visitTime;
		this.visitUid = visitUid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getUid() {
		return this.uid;
	}

	public void setUid(Long uid) {
		this.uid = uid;
	}

	public Date getVisitTime() {
		return this.visitTime;
	}

	public void setVisitTime(Date visitTime) {
		this.visitTime = visitTime;
	}

	public Long getVisitUid() {
		return this.visitUid;
	}

	public void setVisitUid(Long visitUid) {
		this.visitUid = visitUid;
	}

}